# Generated by Django 2.2.28 on 2023-05-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsmeet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetupss',
            name='contact',
        ),
        migrations.AddField(
            model_name='meetupss',
            name='contacts',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
    ]
