# Generated by Django 2.2.28 on 2023-05-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitsubhishi1', models.CharField(max_length=175)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_address', models.EmailField(max_length=175)),
                ('password', models.CharField(max_length=175)),
            ],
        ),
        migrations.DeleteModel(
            name='Model1',
        ),
        migrations.DeleteModel(
            name='Vinay_home',
        ),
    ]
